### ISSUE TITLE
AddGlycan Page

### ISSUE THREAD

**Issue by senaarpinar** [glygener/glyTableMaker-backend#30]
@ReneRanzinger can you tell me how this page should look? 

- "sequence": the page contains the following: 
  * internalID (text field)
  * sequenceFormat dropdown
    * glycoCT
    * WURCS
    * gws
    * CFG
  * sequence (text area)
- "glytoucan": 
  * internalID (text field)
  * glytoucanID (text field)
  *  what else? should we check if the glytoucan id is valid/found when the user clicks "submit"? or retrieve the glycan from glytoucan and show the details (what do we show) to the user, then allow submission.
 - "draw" : do we directly show glycoglyph page (in this case, "submit" button would be in glycoglyph frame - replacing "copy glycan"), or display a form and a button to open "drawing" page (in this case, we come back to the form to show the sequence etc before "submit"). Also should we get "glycoglyph" generated name as the internalId or ask the user to enter an internalID?

**Comment by ReneRanzinger** [comment]
I am not sure I understand. As far es I remember the "Add Glycan" button on the Glycan page should trigger a dropdown with your toplevel options + composition. Depending what the user chooses he will end up with a dialog/page with the corresponding controls. Has that changed?

**Sequence option**
I just noticed that I was not clear "internal ID" meant our auto-increment key. I wanted to make sure that GlyTouCan ID does not become the primary key, since we do not have it in all cases.
Therefore only two input fields:
* Sequence format
* Sequence

**GlyTouCan ID**
Just one input field for the ID and a retrieve button. 

**Draw**
I would onlyshow GlycoGlyph and OK adds the glycan.

**Comment by senaarpinar** [comment]
Yes, there is a dropdown for "Add Glycan". I was trying to see what to show for each case.

As an example, I have this for "sequence" option:

<img width="1240" alt="Screen Shot 2024-01-12 at 1 36 14 PM" src="https://github.com/glygener/glyTableMaker-backend/assets/8181316/b6a93a46-f895-4efc-a9b7-e8574e91f9cb">

**Comment by senaarpinar** [comment]
GlytoucanID case: 
What does the retrieve button do? Retrieve, report errors if any, and add the glycan if there are no errors? Or do we show something on the page after retrieval.

**Comment by ReneRanzinger** [comment]
Its the only button on the dialog/page. It retrieves the glycan, does sequence conversion as needed and add the glycan to the list. If it fails an error is shown with information what went wrong. There is no second confirmation if this glycan should be added. The table should be ordered by recently added after this and the new one will be first in list. If its the wrong one the user can delete it from there.

**Comment by senaarpinar** [comment]
still need to implement composition. see ticket #32
but the other options are implemented
