### ISSUE TITLE
Composition list

### ISSUE THREAD

**Issue by senaarpinar** [glygener/glyTableMaker-backend#31]
Check the glycoinfo composition converter to see the supported monosaccharides and substituents and send the list to @ReneRanzinger

**Comment by senaarpinar** [comment]
@ReneRanzinger 
There is a list in the readme: https://gitlab.com/glycoinfo/glycompconverter

**Comment by senaarpinar** [comment]
and here is the full list from the code as far as I can tell:
https://gitlab.com/glycoinfo/glycompconverter/-/blob/master/src/main/resources/conf/ms/ms_type_snfg?ref_type=heads

**Comment by ReneRanzinger** [comment]
@senaarpinar please test if these are allowed as well
https://gitlab.com/glycoinfo/glycompconverter/-/blob/master/src/main/resources/conf/subst/subst_type?ref_type=heads

**Comment by ReneRanzinger** [comment]
You can find shape and coloring information on the [SNFG](https://www.ncbi.nlm.nih.gov/glycans/snfg.html) webpage. We need the following residues for now (lets use this order):
* Hex
* Glc
* Gal
* Man
* HexNac
* GlcNAc
* GalNAc
* dHex
* Fuc
* Nul0
* Kdn
* Neu5Ac
* Neu5Gc
* Neu	
* Kdo
* HexN
* GlcN
* HexA
* GlcA
* IdoA
* Pen
* Ara
* Xyl
* Rib
* P
* S

For the last two there are not shapes since they are substituents. In this case simple text "<number> x S" can be used.

Please consider that this list will grow over time. So you may want to make it in a way that changes can be done easily (e.g. configuration file) rather than code. I would also recommend having at least two columns (in difference to Nathans tool) and put everything after "Kdo" in the second column.

**Comment by senaarpinar** [comment]
@ReneRanzinger I have a question about parent-child relationship. In Nathan's tool, when the user increments the count for Glucose, the Hexose count is automatically incremented as well since it is the "parent/generic" monosaccharide. I am trying to group them similarly in order to implement that logic. I just wanted to confirm if the following grouping is correct:

* Hex
  * Glc
  * Gal
  * Man
* HexNac
  * GlcNAc
  * GalNAc
* dHex
  * Fuc
* Nul0 - is this the generic type for the next 4? - and does this have the following image? if not, can you link the image?
![image](https://github.com/glygener/glyTableMaker-backend/assets/8181316/378cd7b8-60a3-4c97-be38-6b328bd4fb2c)

* Kdn
* Neu5Ac
* Neu5Gc
* Neu
---
* Kdo
* HexN
  * GlcN
* HexA
  * GlcA
  * IdoA
* Pen
  * Ara
  * Xyl
  * Rib
* P
* S

**Comment by ReneRanzinger** [comment]
@senaarpinar Thanks I forgot to add this. I find this aspect of Nathans tool not intuitive. So no parent child relationship (for now). Each entry in the list works independently. I can have 4xGlc and 0xHex.

Nul0: I am not sure. It should be a white diamond. Yours looks like a flat white diamond which is something different. But I dont know if this is due to the screenshot.

**Comment by senaarpinar** [comment]
ok. I am using a flat structure.
NulO: I copied the image from SNFG website, it is a white diamond.
